################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ELF_SRCS := 
O_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
SECONDARY_SIZE := 
OBJS := 
C_DEPS := 
ASM_DEPS := 
SECONDARY_FLASH := 
S_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src/speaker \
src \
src/hardware \
src/UART \
src/LED_flash \
libs/misc/src \
libs/StdPeriph/src \
libs/CMSIS/src \
FreeRTOS/Source \
FreeRTOS/Source/portable/MemMang \
FreeRTOS/Source/portable/GCC/ARM_CM4F \
FreeRTOS/Settings/demo \
FreeRTOS/Settings/demo/Common/ethernet/uIP/uip-1.0/uip \
FreeRTOS/Settings/demo/Common/ethernet/uIP/uip-1.0/apps/webserver \
FreeRTOS/Settings/demo/Common/ethernet/lwip-1.4.0/src/netif \
FreeRTOS/Settings/demo/Common/ethernet/lwip-1.4.0/src/netif/ppp \
FreeRTOS/Settings/demo/Common/ethernet/lwip-1.4.0/src/core \
FreeRTOS/Settings/demo/Common/ethernet/lwip-1.4.0/src/core/snmp \
FreeRTOS/Settings/demo/Common/ethernet/lwip-1.4.0/src/core/ipv6 \
FreeRTOS/Settings/demo/Common/ethernet/lwip-1.4.0/src/core/ipv4 \
FreeRTOS/Settings/demo/Common/ethernet/lwip-1.4.0/src/api \
FreeRTOS/Settings/demo/Common/ethernet/lwip-1.4.0/ports/win32 \
FreeRTOS/Settings/demo/Common/ethernet/lwip-1.4.0/ports/win32/WinPCap \
FreeRTOS/Settings/demo/Common/ethernet/lwip-1.4.0/ports/MicroBlaze-Ethernet-Lite \
FreeRTOS/Settings/demo/Common/ethernet/lwIP_132/src/netif \
FreeRTOS/Settings/demo/Common/ethernet/lwIP_132/src/netif/ppp \
FreeRTOS/Settings/demo/Common/ethernet/lwIP_132/src/core \
FreeRTOS/Settings/demo/Common/ethernet/lwIP_132/src/core/snmp \
FreeRTOS/Settings/demo/Common/ethernet/lwIP_132/src/core/ipv6 \
FreeRTOS/Settings/demo/Common/ethernet/lwIP_132/src/core/ipv4 \
FreeRTOS/Settings/demo/Common/ethernet/lwIP_132/src/api \
FreeRTOS/Settings/demo/Common/ethernet/lwIP_130/src/netif \
FreeRTOS/Settings/demo/Common/ethernet/lwIP_130/src/netif/ppp \
FreeRTOS/Settings/demo/Common/ethernet/lwIP_130/src/core \
FreeRTOS/Settings/demo/Common/ethernet/lwIP_130/src/core/snmp \
FreeRTOS/Settings/demo/Common/ethernet/lwIP_130/src/core/ipv6 \
FreeRTOS/Settings/demo/Common/ethernet/lwIP_130/src/core/ipv4 \
FreeRTOS/Settings/demo/Common/ethernet/lwIP_130/src/api \
FreeRTOS/Settings/demo/Common/ethernet/lwIP_130/contrib/port/FreeRTOS \
FreeRTOS/Settings/demo/Common/ethernet/lwIP_130/contrib/port/FreeRTOS/ColdFire \
FreeRTOS/Settings/demo/Common/ethernet/lwIP/netif \
FreeRTOS/Settings/demo/Common/ethernet/lwIP/netif/ppp \
FreeRTOS/Settings/demo/Common/ethernet/lwIP/core \
FreeRTOS/Settings/demo/Common/ethernet/lwIP/core/snmp \
FreeRTOS/Settings/demo/Common/ethernet/lwIP/core/ipv4 \
FreeRTOS/Settings/demo/Common/ethernet/lwIP/api \
FreeRTOS/Settings/demo/Common/ethernet/FreeTCPIP \
FreeRTOS/Settings/demo/Common/ethernet/FreeTCPIP/apps/httpd \
FreeRTOS/Settings/demo/Common/ethernet/FreeRTOS-uIP \
FreeRTOS/Settings/demo/Common/drivers/ST/STM32F10xFWLib/src \
FreeRTOS/Settings/demo/Common/drivers/LuminaryMicro \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/utility \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/usart \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/twi \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/tdes \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/tc \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/supc \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/ssc \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/spi \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/slcdc \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/rtt \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/rtc \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/rstc \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/pwmc \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/pmc \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/pit \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/pio \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/mci \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/lcd \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/emac \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/efc \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/eefc \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/dbgu \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/can \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/aic \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/aes \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/peripherals/ac97c \
FreeRTOS/Settings/demo/Common/drivers/Atmel/at91lib/boards/at91sam9xe-ek \
FreeRTOS/Settings/demo/Common/Minimal \
FreeRTOS/Settings/demo/Common/Full \
FreeRTOS/Settings/board \

